---
version: "3.9"
services:
  ovos_phal_tama:
      container_name: ovos_phal_tama
      hostname: ovos_phal_tama
      restart: unless-stopped
      build: https://github.com/dcm0/ovos-PHAL-tama.git
      pull_policy: always
      env_file: /home/ovos/shared/ovos.env
      environment:
        PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
        PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
        TZ: $TZ
      network_mode: host
      devices:
        - /dev/snd
        - /dev/gpiomem
      group_add:
        - "$GPIO_GID"
      volumes:
        - /home/ovos/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
        - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
        - ${TMP_FOLDER}:/tmp/mycroft
        - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro